title: "Open Source Weekends (OSW)"
description: "¡Bienvenid@ a nuestra comunidad!"

exclude:
  - bin
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - docs
  - Gemfile*
  - node_modules
  - package.json
  - Rakefile
  - README.md
  - script
  - test
  - vendor
  - node_modules

permalink: /:path/

collections:
  articles:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/cards/default.png
  - scope:
      path: ""
      type: articles
    values:
      layout: article

plugins:
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown

sass:
  style: :compressed
  sass_dir: assets/css/
  load_paths:
    - node_modules
    - node_modules/**/*/node_modules

branch: gh-pages

github:
  repository_nwo: OSWeekends/welcome.osweekends.com

twitter:
  username: OSWeekends

facebook:
  publisher: https://www.facebook.com/OSWeekends/
